sudo: required
services:
  - docker

before_install:
  - docker build -t sandeepkaukab/docker-react -f Dockerfile.dev .

script:
  - docker run sandeepkaukab/docker-react npm run test -- --coverage
  - dockps=$(docker ps | awk '{print $1}' | tail -1)
  - docker stop ${dockps}
